name: Prebuild iOS for Expo (Manual Only)

on:
  workflow_dispatch:  # Chỉ chạy khi được kích hoạt thủ công

jobs:
  prebuild-ios:
    runs-on: macos-latest  # Chạy trên máy Mac (cần thiết để build iOS)

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: master  # Đảm bảo checkout đúng nhánh master

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Dùng Node.js phiên bản mới

      - name: Install Dependencies
        run: npm install

      - name: Run Expo Prebuild for iOS
        run: npx expo prebuild --platform ios

      - name: Commit and Push iOS folder
        env:
          GH_PAT: ${{ secrets.GH_ACCESS_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git fetch origin master
          git checkout master
          git add ios/
          git commit -m "Auto-generated iOS prebuild via GitHub Actions" || echo "No changes to commit"
          git push https://x-access-token:${GH_ACCESS_TOKEN}@github.com/leekyoung9x/hat-checker.git master
